#pragma once
#include "driver/gpio.h"
#define PENDANT_ENCODER_CLK_GPIO GPIO_NUM_12
#define PENDANT_ENCODER_DT_GPIO GPIO_NUM_13
#define PENDANT_ENCODER_SW_GPIO GPIO_NUM_17
#define PENDANT_BACK_GPIO GPIO_NUM_18
#define PENDANT_ESTOP_GPIO GPIO_NUM_21
#define PENDANT_BATTERY_ADC_GPIO GPIO_NUM_4
